name: Actions workflow

on: 
  schedule:
    - cron: "25 * * * *"
  # push:
  pull_request:
    types: [closed, assigned, opened, reopened]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps: 
      - name: List Files                                   # This will show where our files are stored on the GitHub VM
        run: |                                             # shows path /home/runner/work/github-actions-test/github-actions-test
          pwd
          ls -a
          echo "GitHub Commit Id is: " $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
          echo "${{ github.token }}"                                 
      - name: Checkout
        uses: actions/checkout@v1                          # This authenticates with repository and checkouts into above path.
      - name: List Files After Checkout                   
        run: |                                            
          pwd
          ls -a
      - name: Simple JavaScript Action
        id: greet                                          # We need this Id if we want to reference a step that produces an output
        uses: actions/hello-world-javascript-action@v1     # External published GitHub Action
        with:                                              # With keyword is used to specify the input.
          who-to-greet: James Secker
      - name: Log Greeting Time Output
        run: echo "${{ steps.greet.outputs.time }}"        # The output for this action is called time