name: Context testing
on: [push, pull_request]

jobs:
  dump_contexts_to_log:
    runs-on: ubuntu-latest
    timeout-minutes: 360              # By Default, github jobs have 6 hours to run before being cancelled.  If it needs increasing, you can do this.
    if: github.event_name == 'push'   # We got Event Name from the JSON below which we can use in an expression.
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echho "$GITHUB_CONTEXT"   # Echo is spelt wrong so this job would fail.  Once failed, nothing else runs unless you specify if below.
      - name: Dump job context
        if: failure()                  # This should still run, despite the previous job failing.  You can use continue-on-error: true to run the subsequent steps as well.
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        if: always()                   # This always runs even if any previous steps have failed.
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: echo "$MATRIX_CONTEXT"