name: Shell Commands
on: [pull_request]                           # You can have an array of events for the workflow to run against.

jobs:
  run-shell-command:                 # Make sure to use spaces when you indent, not tabs !
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello World"
      - name: multiline script
        run: | 
          node -v
          npm -v
      - name: python command
        run: |
          import platform
          print(platform.processor())
        shell: python                  # You need to make sure you use the correct shell otherwise this will error.
  run-windows-command:
    runs-on: windows-latest
    needs: ["run-shell-command"]       # If we don't want to run these jobs in parallel but in sequence, use this.
    steps:
      - name: Directory Powershell
        run: Get-Location
      - name: Directory Bash
        run: pwd
        shell: bash